### ISSUE TITLE
cachedAccessories causing duplicate UUID with homebridge-cmdswitch2

### ISSUE THREAD

**Issue by jarrah31** [hassio-addons/addon-homebridge#13]
I'm not sure if this is a cmdswitch2 or homebridge issue, so I've posted the problem on both projects, with the other one being here: https://github.com/luisiam/homebridge-cmdswitch2/issues/8#issuecomment-327000803

Using the cmdswitch2 plugin, if I restart the homebridge service the duplicate UUID error occurs. If I delete the /config/homebridge/accessories/cachedAccessories file and restart, it works ok. Restart the service again and it fails. 

Multiple people on this thread have experienced the same problem: https://community.home-assistant.io/t/homekit-location-to-trigger-automations-in-home-assistant-using-a-software-switch-requires-no-homekit-hardware/17235 

The latest version of hassio (using ResinOS image) with the homebridge add-on is being used. 

Within Options I have the following:
```json
 {
  "debug": false,
  "plugins": [
    "homebridge-cmdswitch2"
  ]
}
```

After accessing hassio via SSH, /config/homebridge/config.json is modified with the following:

```json
{
  "bridge": {
    "name": "Home Assistant",
    "username": "00:00:00:00:00:00",  #removed values
    "port": 51826,
    "pin": "000-00-000"  #removed values
  },
  "description": "Homebridge for Home Assistant",
  "accessories": [],
  "platforms": [
    {
      "platform": "HomeAssistant",
       
       .... Shortened for this comment
       
        "sensor",
        "switch"
      ],
      "logging": true
    }, {
      "platform": "cmdSwitch2",
      "name": "CMD switch",
      "switches": [{
        "name": "User isHome",
        "on_cmd": "/config/homebridge/userhome.sh",
        "off_cmd": "/config/homebridge/useraway.sh",
        "state_cmd": "/config/homebridge/userstatus.sh",
        "polling": "true"
      }]
    }]
}
```

The logs show the following error:

```
[9/4/2017, 5:42:17 PM] Loaded plugin: homebridge-cmdswitch2
[9/4/2017, 5:42:17 PM] Registering platform 'homebridge-cmdswitch2.cmdSwitch2'
[9/4/2017, 5:42:17 PM] ---
[9/4/2017, 5:42:18 PM] Loaded plugin: homebridge-homeassistant
[9/4/2017, 5:42:18 PM] Registering platform 'homebridge-homeassistant.HomeAssistant'
[9/4/2017, 5:42:18 PM] ---
[9/4/2017, 5:42:18 PM] Loaded config.json with 0 accessories and 2 platforms.
[9/4/2017, 5:42:18 PM] ---
[9/4/2017, 5:42:18 PM] Loading 2 platforms...
[9/4/2017, 5:42:18 PM] [HomeAssistant] Initializing HomeAssistant platform...
[9/4/2017, 5:42:18 PM] [HomeAssistant] Fetching HomeAssistant devices.
[9/4/2017, 5:42:18 PM] [CMD switch] Initializing cmdSwitch2 platform...
[9/4/2017, 5:42:18 PM] Loading 0 accessories...
[9/4/2017, 5:42:18 PM] [CMD switch] Initializing platform accessory 'User isHome'...
/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:256
      throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
      ^
Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 3dd34efe-097b-4b8b-a688-352f08cd38d6
    at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:256:13)
    at Bridge.Accessory.addBridgedAccessories (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:282:10)
    at Server._handleRegisterPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:437:16)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:36:10)
```

**Comment by bonanitech** [comment]
I have the same problem when using the homebridge-cmdswitch2 plugin with this addon

**Comment by frenck** [comment]
Seems like the used plugin is reporting multiple devices with the same UUID.
Not sure this is an issue with this add-on.

Have you tried changing the `username` to some other random (valid) value?

**Comment by frenck** [comment]
I'm closing this issue since it is running stale.
If you feel the need to discuss this further, please feel free to re-open this issue.
