### ISSUE TITLE
install failed after upgrade HA to 0.55.0

### ISSUE THREAD

**Issue by sephrioth** [hassio-addons/addon-homebridge#24]
## Problem/Motivation

> start failed

## Expected behavior

> start success

## Actual behavior

>
starting version 3.2.2
[ADD-ON] Installing Homebridge plugin homebridge-harmonyhub
path.js:1138
      if (i >} 0)
             ^
SyntaxError: Unexpected token }
    at runInThisContext (bootstrap_node.js:437:20)
    at NativeModule.compile (bootstrap_node.js:525:18)
    at Function.NativeModule.require (bootstrap_node.js:471:18)
    at startup (bootstrap_node.js:128:35)
    at bootstrap_node.js:542:3
[ADD-ON][ERROR] An error occured!
!!! ERROR: Failed installing Homebridge plugin homebridge-harmonyhub

## Steps to reproduce

> start homebridge

## Proposed changes

> (If you have a proposed change, workaround or fix, describe the rationale behind it)

**Comment by sephrioth** [comment]
A clean installation solved problem.
