### ISSUE TITLE
Can't install addon

### ISSUE THREAD

**Issue by bonanitech** [hassio-addons/addon-homebridge#25]
I'm receiving the following messages when trying to install this addon on a new Hass.io box I'm building:

```
17-10-09 22:40:57 INFO (SyncWorker_5) [hassio.dock.addon] Start build d89827df/amd64-addon-homebridge:1.0.3
17-10-09 22:40:57 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 422, in start
    resp = yield from self._request_handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web.py", line 306, in _handle
    resp = yield from handler(request)
  File "/usr/lib/python3.6/site-packages/hassio/api/util.py", line 31, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/hassio/addons/addon.py", line 466, in install
    if not await self.docker.install(self.last_version):
  File "/usr/lib/python3.6/site-packages/hassio/dock/util.py", line 18, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/hassio/dock/addon.py", line 198, in _install
    return self._build(tag)
  File "/usr/lib/python3.6/site-packages/hassio/dock/addon.py", line 211, in _build
    image = self.docker.images.build(**build_env.get_docker_args(tag))
  File "/usr/lib/python3.6/site-packages/docker/models/images.py", line 175, in build
    raise BuildError(chunk['error'])
docker.errors.BuildError: invalid reference format: repository name must be lowercase
```

What am I doing wrong?

**Comment by bonanitech** [comment]
Just tried to install on Ubuntu, same problem:

```
17-10-10 17:27:57 INFO (MainThread) [hassio.addons.git] Clone addon https://github.com/hassio-addons/addon-homebridge repository
17-10-10 17:27:57 INFO (MainThread) [hassio.addons] Load addons: 17 all - 1 new - 0 remove
17-10-10 17:28:02 INFO (MainThread) [hassio.addons.git] Pull addon https://github.com/home-assistant/hassio-addons repository
17-10-10 17:28:02 INFO (MainThread) [hassio.addons.git] Pull addon https://github.com/hassio-addons/addon-homebridge repository
17-10-10 17:28:03 INFO (MainThread) [hassio.addons] Load addons: 17 all - 0 new - 0 remove
17-10-10 17:28:06 INFO (MainThread) [hassio.addons.addon] Create Home-Assistant addon data folder /data/addons/data/d89827df_homebridge
17-10-10 17:28:06 INFO (SyncWorker_3) [hassio.dock.addon] Start build d89827df/amd64-addon-homebridge:1.0.3
17-10-10 17:28:06 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 422, in start
    resp = yield from self._request_handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web.py", line 306, in _handle
    resp = yield from handler(request)
  File "/usr/lib/python3.6/site-packages/hassio/api/util.py", line 31, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/hassio/addons/addon.py", line 466, in install
    if not await self.docker.install(self.last_version):
  File "/usr/lib/python3.6/site-packages/hassio/dock/util.py", line 18, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/hassio/dock/addon.py", line 198, in _install
    return self._build(tag)
  File "/usr/lib/python3.6/site-packages/hassio/dock/addon.py", line 211, in _build
    image = self.docker.images.build(**build_env.get_docker_args(tag))
  File "/usr/lib/python3.6/site-packages/docker/models/images.py", line 175, in build
    raise BuildError(chunk['error'])
docker.errors.BuildError: invalid reference format: repository name must be lowercase
```

**Comment by bonanitech** [comment]
@frenck What packages do I need to have installed for this addon to work on a Debian amd64?

**Comment by frenck** [comment]
You have added `https://github.com/hassio-addons/addon-homebridge` as the add-on repository.
Please remove it and use `https://github.com/hassio-addons/repository`, as stated in the documentation of this add-on.

**Comment by bonanitech** [comment]
Oops! Shame on me.

**Comment by frenck** [comment]
Hehe don’t worry, stuff happens :)
