### ISSUE TITLE
Temperature incorrectly passing to HomeKit

### ISSUE THREAD

**Issue by erfind** [hassio-addons/addon-homebridge#31]
The temperature being passed from the nest add on through the homebridge is incorrect. It's set to 72°F but shows 169°F in the Home app...any ideas it shows up correctly in Home Assistant. 

![Image](https://i.imgur.com/Iosv236.jpg)

**Comment by erfind** [comment]
I searched logs and found this:

2017-10-12 20:43:09 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/tasks.py", line 181, in _step
    result = coro.throw(exc)
  File "/usr/lib/python3.6/site-packages/homeassistant/core.py", line 1025, in _event_to_service_call
    yield from service_handler.func(service_call)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/climate/__init__.py", line 331, in async_temperature_set_service
    yield from climate.async_set_temperature(**kwargs)
  File "/usr/lib/python3.6/asyncio/futures.py", line 331, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 244, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 244, in result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/climate/nest.py", line 158, in set_temperature
    self.device.target = temp
  File "/usr/lib/python3.6/site-packages/nest/nest.py", line 510, in target
    self._set('devices/thermostats', data)
  File "/usr/lib/python3.6/site-packages/nest/nest.py", line 168, in _set
    response = self._nest_api._put(path=path, data=data)
  File "/usr/lib/python3.6/site-packages/nest/nest.py", line 1590, in _put
    return self._request('PUT', path, data=data)
  File "/usr/lib/python3.6/site-packages/nest/nest.py", line 1582, in _request
    raise APIError(response)
nest.nest.APIError: blocked

**Comment by frenck** [comment]
Hi @erfind,

This seems like an issue with the Nest component (may be initiated by Homebridge). This issue is not within the domain of this add-on. I suggest you'd open an issue at the Home Assistant or Homebridge repository.
