### ISSUE TITLE
Homebridge DNS service error (log)

### ISSUE THREAD

**Issue by kolossboss** [hassio-addons/addon-homebridge#35]
## Problem/Motivation

> Homebridge not starting

## Expected behavior

> Running homebridge addon

## Actual behavior

> Homebridge is completely loading , but at the End is an DNS error and Homebridge is stops running.

## Steps to reproduce

> I only restarted the addon

## Proposed changes

A possible fix/workaround is the reinstall avahi daemon `sudo apt-get install avahi-daemon avahi-discover libnss-mdns libavahi-compat-libdnssd-dev`
But how is this possible on Hass.io?

LOG:
```
starting version 3.2.2
[ADD-ON] Ensuring old PID files are absent
[ADD-ON] Ensuring D-Bus unique ID exists
[ADD-ON] Starting D-Bus daemon
[ADD-ON] Starting Avahi daemon
Found user 'avahi' (UID 86) and group 'avahi' (GID 86).
Successfully dropped root privileges.
write(): No space left on device
Failed to create PID file: No space left on device
[ADD-ON] Applying HAP NodeJS IPV6 HOTFIX
patching file /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js
[ADD-ON] Starting Homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[10/20/2017, 11:03:39 AM] Loaded plugin: homebridge-homeassistant
[10/20/2017, 11:03:39 AM] Registering platform 'homebridge-homeassistant.HomeAssistant'
[10/20/2017, 11:03:39 AM] ---
[10/20/2017, 11:03:39 AM] Loaded config.json with 0 accessories and 1 platforms.
[10/20/2017, 11:03:39 AM] ---
[10/20/2017, 11:03:39 AM] Loading 1 platforms...
[10/20/2017, 11:03:39 AM] [HomeAssistant] Initializing HomeAssistant platform...
[10/20/2017, 11:03:39 AM] [HomeAssistant] Fetching HomeAssistant devices.
[10/20/2017, 11:03:39 AM] Loading 0 accessories...
[10/20/2017, 11:03:41 AM] [HomeAssistant] Initializing platform accessory 'deaktiviere Alarmanlage'...
[10/20/2017, 11:03:41 AM] [HomeAssistant] Initializing platform accessory 'aktiviere Alarmanlage'...
[10/20/2017, 11:03:41 AM] [HomeAssistant] Initializing platform accessory 'Ad Blocker'...
[10/20/2017, 11:03:41 AM] [HomeAssistant] Initializing platform accessory 'Jalousie_Wohnzimmer'...
[10/20/2017, 11:03:41 AM] [HomeAssistant] Initializing platform accessory 'Weihnachtsstern'...
[10/20/2017, 11:03:41 AM] [HomeAssistant] Initializing platform accessory 'Alarm ausgeloest'...
[10/20/2017, 11:03:41 AM] [HomeAssistant] Initializing platform accessory 'Drucker'...
[10/20/2017, 11:03:41 AM] [HomeAssistant] Initializing platform accessory 'Ambilight'...
[10/20/2017, 11:03:41 AM] [HomeAssistant] Initializing platform accessory 'Jalousie_Esszimmer'...
[10/20/2017, 11:03:41 AM] [HomeAssistant] Initializing platform accessory 'Lichterkette_draussen'...
[10/20/2017, 11:03:41 AM] [HomeAssistant] Initializing platform accessory 'Lichterkette'...
[10/20/2017, 11:03:41 AM] [HomeAssistant] Initializing platform accessory 'Venta'...
[10/20/2017, 11:03:41 AM] [HomeAssistant] Initializing platform accessory 'Jalousie_Kueche'...
[10/20/2017, 11:03:41 AM] [HomeAssistant] Initializing platform accessory 'Luftbefeuchter Schlafzimmer'...
[10/20/2017, 11:03:41 AM] [HomeAssistant] Initializing platform accessory 'Luftbefeuchter Kira'...
[10/20/2017, 11:03:41 AM] [HomeAssistant] Initializing platform accessory 'Mobil Sonos'...
[10/20/2017, 11:03:41 AM] [HomeAssistant] Initializing platform accessory 'Wohnzimmer Sonos'...
[10/20/2017, 11:03:41 AM] [HomeAssistant] Initializing platform accessory 'Stehlampe'...
[10/20/2017, 11:03:41 AM] [HomeAssistant] Initializing platform accessory 'Flurlampe'...
[10/20/2017, 11:03:41 AM] [HomeAssistant] Initializing platform accessory 'Jalousie HWR'...
[10/20/2017, 11:03:41 AM] [HomeAssistant] Initializing platform accessory 'Küchen Lampe'...
[10/20/2017, 11:03:41 AM] [HomeAssistant] Initializing platform accessory 'Temperatursensor_Kueche'...
[10/20/2017, 11:03:41 AM] [HomeAssistant] Initializing platform accessory 'Helligskeitssensor_Kueche'...
[10/20/2017, 11:03:41 AM] [HomeAssistant] Initializing platform accessory 'Wohnzimmerlampe'...
[10/20/2017, 11:03:41 AM] [HomeAssistant] Initializing platform accessory 'Jalousie Schiebetür'...
[10/20/2017, 11:03:41 AM] [HomeAssistant] Initializing platform accessory 'Brunnenpumpe'...
[10/20/2017, 11:03:41 AM] [HomeAssistant] Initializing platform accessory 'Ladestation'...
[10/20/2017, 11:03:41 AM] [HomeAssistant] Initializing platform accessory 'Kompressor'...
[10/20/2017, 11:03:41 AM] [HomeAssistant] Initializing platform accessory 'Carport Steckdose'...
[10/20/2017, 11:03:41 AM] [HomeAssistant] Initializing platform accessory 'Temperatur Wohnzimmer'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 853-81-325 │     
    └────────────┘     
                       
/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56
  dns_sd.DNSServiceRegister(self.serviceRef, flags, ifaceIdx, name,
         ^
Error: dns service error: unknown
    at new Advertisement (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:64:10)
    at Advertiser.startAdvertising (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Advertiser.js:43:30)
    at Bridge.Accessory._onListening (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:575:20)
    at emitOne (events.js:96:13)
    at HAPServer.emit (events.js:191:7)
    at HAPServer._onListening (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:190:8)
    at emitOne (events.js:96:13)
    at EventedHTTPServer.emit (events.js:191:7)
    at EventedHTTPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:65:10)
```

**Comment by kolossboss** [comment]
thanks to @frenck 
I missed this entry

```
write(): No space left on device
Failed to create PID file: No space left on device
```

now its working.

**Comment by frenck** [comment]
No problem! Solved this in the Home Assistant community forums (issue was cross-posted).
