### ISSUE TITLE
Won't start; sed: unmatched '/'

### ISSUE THREAD

**Issue by siewyc** [hassio-addons/addon-homebridge#45]
Hi frenck, I have the following error while starting up homebridge 2.0. Could you help me with the issue please?

Raspberry pi 3 
hostOS 1.1 
Supervisor 0.72
HA 0.56.0

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 10-homebridge: applying... 
[fix-attrs.d] 10-homebridge: exited 0.
[fix-attrs.d] 20-dbus: applying... 
[fix-attrs.d] 20-dbus: exited 0.
[fix-attrs.d] 30-avahi: applying... 
[fix-attrs.d] 30-avahi: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Homebridge v2.0.0
 HomeKit support for your Home Assistant instance using Homebridge
 From: Community Hass.io Add-ons
 By: Franck Nijhof <frenck@addons.community>
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to DEBUG
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 
DEBUG: Requested API resource: http://hassio/supervisor/ping
DEBUG: API HTTP Response code: 200
DEBUG: API Response: {"result": "ok", "data": {}}
DEBUG: Requested API resource: http://hassio/addons/a0d7b954_homebridge/info
DEBUG: API HTTP Response code: 200
DEBUG: API Response: {"result": "ok", "data": {"name": "Homebridge", "description": "HomeKit support for your Home Assistant instance using Homebridge", "version": "2.0.0", "auto_update": false, "repository": "a0d7b954", "last_version": "2.0.0", "state": "started", "boot": "auto", "options": {"log_level": "debug", "avahi_interfaces": "", "avahi_hostname": "", "avahi_domainname": "local", "enable_ipv6": true, "packages": [], "init_commands": [], "plugins": []}, "url": "https://github.com/hassio-addons/addon-homebridge", "detached": false, "build": false, "network": null, "host_network": true, "privileged": [], "devices": null, "logo": false, "webui": null, "stdin": false, "hassio_api": true, "homeassistant_api": true, "gpio": false, "audio": false, "audio_input": null, "audio_output": null}}
DEBUG: Filtering response using: .version
DEBUG: Requested API resource: http://hassio/addons/a0d7b954_homebridge/info
DEBUG: API HTTP Response code: 200
DEBUG: API Response: {"result": "ok", "data": {"name": "Homebridge", "description": "HomeKit support for your Home Assistant instance using Homebridge", "version": "2.0.0", "auto_update": false, "repository": "a0d7b954", "last_version": "2.0.0", "state": "started", "boot": "auto", "options": {"log_level": "debug", "avahi_interfaces": "", "avahi_hostname": "", "avahi_domainname": "local", "enable_ipv6": true, "packages": [], "init_commands": [], "plugins": []}, "url": "https://github.com/hassio-addons/addon-homebridge", "detached": false, "build": false, "network": null, "host_network": true, "privileged": [], "devices": null, "logo": false, "webui": null, "stdin": false, "hassio_api": true, "homeassistant_api": true, "gpio": false, "audio": false, "audio_input": null, "audio_output": null}}
DEBUG: Filtering response using: .last_version
INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 20-dbus.sh: executing... 
[cont-init.d] 20-dbus.sh: exited 0.
[cont-init.d] 30-avahi.sh: executing... 
DEBUG: Detected Avahi interfaces: eth0
wlan0
sed: unmatched '/'
[cont-init.d] 30-avahi.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by drock1985** [comment]
There is a temporary workaround. See this thread for full details. https://github.com/hassio-addons/addon-homebridge/issues/40

What you have to do is enter a hostname in the avahi-hostname field. Save it, then restart homebridge. I had the same issue as you and everything is working great now after doing that.

**Comment by siewyc** [comment]
Hi drock, thanks for your advice, I've already tried that solution but it doesn't work for me in this case.

**Comment by drock1985** [comment]
No problem siewyc.

One other question though. I see you use a Rpi3; are you using the wifi by any chance?

**Comment by siewyc** [comment]
Nope, it's connected with an ethernet cable

**Comment by drock1985** [comment]
Whats the full output of your options? This is mine (no addons)

{
  "log_level": "info",
  "avahi_interfaces": "",
  "avahi_hostname": "hassio",
  "avahi_domainname": "local",
  "enable_ipv6": true,
  "packages": [],
  "init_commands": [],
  "plugins": []
}

**Comment by siewyc** [comment]
Here's mine:

{
"log_level": "debug",
"avahi_interfaces": "",
"avahi_hostname": "hassio",
"avahi_domainname": "local",
"enable_ipv6": true,
"packages": [],
"init_commands": [],
"plugins": [
"homebridge-aqara"
]
}

**Comment by drock1985** [comment]
Have you tried running homebridge without the addon to see if it boots?

**Comment by siewyc** [comment]
Yes, I've tried that already :(

**Comment by frenck** [comment]
Hi @siewyc,

Thank you for this bug report. You wrote that you had connected your PI using ethernet, but it seems like it is connected to WiFi as well (simultaneously). Which breaks stuff, so that needs fixing.

Looking at your configuration, it seems like you have set the `avahi_hostname`, which is not needed in your case since the add-on is able to connect to the API of Hass.io.

So my suggestion to workaround this issue would be:

```json
{
  "log_level": "debug",
  "avahi_interfaces": "",
  "avahi_hostname": "hassio",
  "avahi_domainname": "local",
  "enable_ipv6": true,
  "packages": [],
  "init_commands": [],
  "plugins": [
    "homebridge-aqara"
  ]
}
```

PS, there is another issue open concerning the use of plugins. You'd probably need to add `git` to the `packages` (see #44).

**Comment by siewyc** [comment]
Hi @frenck,

Thank you for your reply. You were right that my pi 3 was connected to both wlan and ethernet. I have since changed the setting to connect via ethernet only. However, this is the new error that I have:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 10-homebridge: applying... 
[fix-attrs.d] 10-homebridge: exited 0.
[fix-attrs.d] 20-dbus: applying... 
[fix-attrs.d] 20-dbus: exited 0.
[fix-attrs.d] 30-avahi: applying... 
[fix-attrs.d] 30-avahi: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Homebridge v2.0.0
 HomeKit support for your Home Assistant instance using Homebridge
 From: Community Hass.io Add-ons
 By: Franck Nijhof <frenck@addons.community>
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to DEBUG
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 
DEBUG: Requested API resource: http://hassio/supervisor/ping
DEBUG: API HTTP Response code: 200
DEBUG: API Response: {"result": "ok", "data": {}}
DEBUG: Requested API resource: http://hassio/addons/a0d7b954_homebridge/info
DEBUG: API HTTP Response code: 200
DEBUG: API Response: {"result": "ok", "data": {"name": "Homebridge", "description": "HomeKit support for your Home Assistant instance using Homebridge", "version": "2.0.0", "auto_update": false, "repository": "a0d7b954", "last_version": "2.0.0", "state": "started", "boot": "auto", "options": {"log_level": "debug", "avahi_interfaces": "", "avahi_hostname": "hassio", "avahi_domainname": "local", "enable_ipv6": true, "packages": [], "init_commands": [], "plugins": ["homebridge-mi-aqara"]}, "url": "https://github.com/hassio-addons/addon-homebridge", "detached": false, "build": false, "network": null, "host_network": true, "privileged": [], "devices": null, "logo": false, "webui": null, "stdin": false, "hassio_api": true, "homeassistant_api": true, "gpio": false, "audio": false, "audio_input": null, "audio_output": null}}
DEBUG: Filtering response using: .version
DEBUG: Requested API resource: http://hassio/addons/a0d7b954_homebridge/info
DEBUG: API HTTP Response code: 200
DEBUG: API Response: {"result": "ok", "data": {"name": "Homebridge", "description": "HomeKit support for your Home Assistant instance using Homebridge", "version": "2.0.0", "auto_update": false, "repository": "a0d7b954", "last_version": "2.0.0", "state": "started", "boot": "auto", "options": {"log_level": "debug", "avahi_interfaces": "", "avahi_hostname": "hassio", "avahi_domainname": "local", "enable_ipv6": true, "packages": [], "init_commands": [], "plugins": ["homebridge-mi-aqara"]}, "url": "https://github.com/hassio-addons/addon-homebridge", "detached": false, "build": false, "network": null, "host_network": true, "privileged": [], "devices": null, "logo": false, "webui": null, "stdin": false, "hassio_api": true, "homeassistant_api": true, "gpio": false, "audio": false, "audio_input": null, "audio_output": null}}
DEBUG: Filtering response using: .last_version
INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 20-dbus.sh: executing... 
[cont-init.d] 20-dbus.sh: exited 0.
[cont-init.d] 30-avahi.sh: executing... 
DEBUG: Detected Avahi interfaces: wlan0
[cont-init.d] 30-avahi.sh: exited 0.
[cont-init.d] 50-config.sh: executing... 
[cont-init.d] 50-config.sh: exited 0.
[cont-init.d] 60-ipv6-hotfix.sh: executing... 
[cont-init.d] 60-ipv6-hotfix.sh: exited 0.
[cont-init.d] 80-user-packages.sh: executing... 
[cont-init.d] 80-user-packages.sh: exited 0.
[cont-init.d] 81-user-scripts.sh: executing... 
[cont-init.d] 81-user-scripts.sh: exited 0.
[cont-init.d] 82-user-plugins.sh: executing... 
+ homebridge-mi-aqara@0.6.1
added 1 package in 3.073s
[cont-init.d] 82-user-plugins.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
starting version 3.2.2
[services.d] done.
Found user 'avahi' (UID 86) and group 'avahi' (GID 86).
Successfully dropped root privileges.
avahi-daemon 0.6.32 starting up.
chroot.c: chroot() helper started
WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
Successfully called chroot().
Successfully dropped remaining capabilities.
chroot.c: chroot() helper got command 02
No service file found in /etc/avahi/services.
*** WARNING: Detected another IPv4 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***
*** WARNING: Detected another IPv6 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***
Joining mDNS multicast group on interface hassio.IPv6 with address fe80::42:f2ff:fe71:1d4f.
New relevant interface hassio.IPv6 for mDNS.
Joining mDNS multicast group on interface hassio.IPv4 with address 172.30.32.1.
New relevant interface hassio.IPv4 for mDNS.
Joining mDNS multicast group on interface wlan0.IPv6 with address fe80::7896:64da:55ca:f74e.
New relevant interface wlan0.IPv6 for mDNS.
Joining mDNS multicast group on interface wlan0.IPv4 with address 192.168.0.32.
New relevant interface wlan0.IPv4 for mDNS.
Network interface enumeration completed.
Registering new address record for fe80::42:f2ff:fe71:1d4f on hassio.*.
Registering new address record for 172.30.32.1 on hassio.*.
Registering new address record for fe80::7896:64da:55ca:f74e on wlan0.*.
Registering new address record for 192.168.0.32 on wlan0.*.
Received packet from invalid interface.
Received packet from invalid interface.
Received packet from invalid interface.
Received conflicting record [hassio.local	IN	AAAA fe80::2953:5739:259a:85dd ; ttl=120] with local record to be. Withdrawing.
Withdrawing address record for fe80::42:f2ff:fe71:1d4f on hassio.
Withdrawing address record for 172.30.32.1 on hassio.
Withdrawing address record for 192.168.0.32 on wlan0.
Host name conflict, retrying with hassio-2
Registering new address record for fe80::42:f2ff:fe71:1d4f on hassio.*.
Registering new address record for 172.30.32.1 on hassio.*.
Registering new address record for fe80::7896:64da:55ca:f74e on wlan0.*.
Registering new address record for 192.168.0.32 on wlan0.*.
..
..
```
Basically, it goes on and endless loop with host name conflict, retrying with hassio-3 then hassio-4 all the way to 20... 30..

**Comment by frenck** [comment]
Try setting `avahi_interfaces`  to `eth0`.

**Comment by siewyc** [comment]
I have done that but it's still the same problem. 

the error message is the same but wlan0 is replaced with eth0 instead.

**Comment by frenck** [comment]
It is a puzzle, right now... you could try both at the same time; like this: `eth0,wlan0`.
Also disable IPv6, there are known problems with the stack you are using. Change `enable_ipv6` to `false`.

**Comment by siewyc** [comment]
I've tried rebooting the host and it seems that there is some success. Homebridge managed to run for a while before encountering an error.


```
[10/22/2017, 11:59:12 PM] [HomeAssistant] Initializing platform accessory 'Cube rotate - Spotify Volume'...
[10/22/2017, 11:59:12 PM] [HomeAssistant] Initializing platform accessory 'Turn on diffuser'...
[10/22/2017, 11:59:12 PM] [HomeAssistant] Initializing platform accessory 'Turn off all lights'...
[10/22/2017, 11:59:12 PM] [HomeAssistant] Initializing platform accessory 'Turn on fan'...
[10/22/2017, 11:59:12 PM] [HomeAssistant] Initializing platform accessory 'Turn off all lights when single click'...
[10/22/2017, 11:59:12 PM] [HomeAssistant] Initializing platform accessory 'Toggle bed light'...
[10/22/2017, 11:59:12 PM] [HomeAssistant] Initializing platform accessory 'Turn on all lights when double click'...
[10/22/2017, 11:59:12 PM] [HomeAssistant] Initializing platform accessory 'all automations'...
[10/22/2017, 11:59:12 PM] [HomeAssistant] Initializing platform accessory 'Temperature'...
[10/22/2017, 11:59:12 PM] [HomeAssistant] Initializing platform accessory 'Temperature'...
[10/22/2017, 11:59:12 PM] [HomeAssistant] Initializing platform accessory 'Humidity'...
[10/22/2017, 11:59:12 PM] [HomeAssistant] Initializing platform accessory 'Bedroom Motion'...
[10/22/2017, 11:59:12 PM] [HomeAssistant] Initializing platform accessory 'Bedroom Door'...
[10/22/2017, 11:59:12 PM] [HomeAssistant] Initializing platform accessory 'Staircase Motion'...
[10/22/2017, 11:59:12 PM] [HomeAssistant] Initializing platform accessory 'Spotify'...
[10/22/2017, 11:59:12 PM] [HomeAssistant] Initializing platform accessory 'Fan'...
[10/22/2017, 11:59:12 PM] [HomeAssistant] Initializing platform accessory 'Diffuser'...
[10/22/2017, 11:59:12 PM] [HomeAssistant] Initializing platform accessory 'all switches'...
[10/22/2017, 11:59:12 PM] [HomeAssistant] Initializing platform accessory 'Ceiling Light'...
[10/22/2017, 11:59:12 PM] [HomeAssistant] Initializing platform accessory 'Floor Lamp'...
[10/22/2017, 11:59:12 PM] [HomeAssistant] Initializing platform accessory 'Light Strip'...
[10/22/2017, 11:59:12 PM] [HomeAssistant] Initializing platform accessory 'Gateway light'...
[10/22/2017, 11:59:12 PM] [HomeAssistant] Initializing platform accessory 'all lights'...
[10/22/2017, 11:59:12 PM] [HomeAssistant] Initializing platform accessory 'all devices'...
[10/22/2017, 11:59:12 PM] [HomeAssistant] Initializing platform accessory 'Jerald'...
[10/22/2017, 11:59:12 PM] [HomeAssistant] Initializing platform accessory 'iPhone 5'...
[10/22/2017, 11:59:12 PM] [HomeAssistant] Initializing platform accessory 'iPad Air'...
[10/22/2017, 11:59:12 PM] [HomeAssistant] Initializing platform accessory 'OGCHUNG'...
[10/22/2017, 11:59:12 PM] [HomeAssistant] Initializing platform accessory 'Jerald’s MacBook Pro'...
[10/22/2017, 11:59:12 PM] [HomeAssistant] Initializing platform accessory 'Chung og af'...
[10/22/2017, 11:59:12 PM] [HomeAssistant] Initializing platform accessory 'HUAWEI Mate 9 Pro'...
[10/22/2017, 11:59:12 PM] [HomeAssistant] Initializing platform accessory 'So loud mannnn'...
[10/22/2017, 11:59:12 PM] [HomeAssistant] Initializing platform accessory 'JS iPhone 6'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 314-89-098 │     
    └────────────┘     
                       
[10/22/2017, 11:59:12 PM] Homebridge is running on port 51826.
[10/22/2017, 11:59:12 PM] [HomeAssistant] Received event: {"event_type": "state_changed", "data": {"entity_id": "sensor.worldclock_sensor", "old_state": {"entity_id": "sensor.worldclock_sensor", "state": "06:58", "attributes": {"friendly_name": "Singapore Time", "icon": "mdi:clock"}, "last_changed": "2017-10-22T22:58:41.903234+00:00", "last_updated": "2017-10-22T22:58:41.903234+00:00"}, "new_state": {"entity_id": "sensor.worldclock_sensor", "state": "06:59", "attributes": {"friendly_name": "Singapore Time", "icon": "mdi:clock"}, "last_changed": "2017-10-22T22:59:12.406404+00:00", "last_updated": "2017-10-22T22:59:12.406404+00:00"}}, "origin": "LOCAL", "time_fired": "2017-10-22T22:59:12.406526+00:00"}
Withdrawing address record for 172.30.32.1 on hassio.
Withdrawing address record for fe80::aed3:dbda:67b8:853a on eth0.
Withdrawing address record for 192.168.0.47 on eth0.
Host name conflict, retrying with hassio-17
Registering new address record for fe80::42:53ff:feda:d296 on hassio.*.
Registering new address record for 172.30.32.1 on hassio.*.
Registering new address record for fe80::aed3:dbda:67b8:853a on eth0.*.
Registering new address record for 192.168.0.47 on eth0.*.
[10/22/2017, 11:59:24 PM] [HomeAssistant] Received event: {"event_type": "platform_discovered", "data": {"service": "load_platform.light", "platform": "hue", "discovered": {"host": "192.168.0.32", "port": 8300, "ssdp_description": "http://192.168.0.32:8300/description.xml", "name": "HASS Bridge (192.168.0.32)", "model_name": "Philips hue bridge 2015", "model_number": "BSB002", "serial": "1234"}}, "origin": "LOCAL", "time_fired": "2017-10-22T22:59:22.537505+00:00"}
[10/22/2017, 11:59:24 PM] [HomeAssistant] Received event: {"event_type": "platform_discovered", "data": {"service": "load_platform.media_player", "platform": "soundtouch", "discovered": {"host": "192.168.0.28", "port": 8090, "hostname": "b0d5cc55336b.local.", "properties": {"DESCRIPTION": "<<REPLACE-EG-TIAGAN>", "MAC": "B0D5CC55336B", "MANUFACTURER": "Bose Corporation", "MODEL": " < sysconfig - put#here>-101x"}}}, "origin": "LOCAL", "time_fired": "2017-10-22T22:59:22.544059+00:00"}
[10/22/2017, 11:59:24 PM] [HomeAssistant] Received event: {"event_type": "platform_discovered", "data": {"service": "belkin_wemo", "discovered": {"host": "192.168.0.25", "port": 49153, "ssdp_description": "http://192.168.0.25:49153/setup.xml", "name": "Diffuser", "model_name": "Socket", "model_number": "1.0", "serial": "221602K11000A7", "mac_address": "149182046048"}}, "origin": "LOCAL", "time_fired": "2017-10-22T22:59:22.554583+00:00"}
[10/22/2017, 11:59:24 PM] [HomeAssistant] Received event: {"event_type": "platform_discovered", "data": {"service": "xiaomi_gw", "discovered": {"host": "192.168.0.22", "port": 54321, "hostname": "lumi-gateway-v3_miio44728898.local.", "properties": {"epoch": "1", "mac": "f0b4299af831"}, "mac_address": "f0b4299af831"}}, "origin": "LOCAL", "time_fired": "2017-10-22T22:59:22.566169+00:00"}
[10/22/2017, 11:59:24 PM] [HomeAssistant] Received event: {"event_type": "platform_discovered", "data": {"service": "load_platform.light", "platform": "yeelight", "discovered": {"host": "192.168.0.21", "port": 54321, "hostname": "yeelink-light-color1_miio48214162.local.", "properties": {"epoch": "1", "mac": "286c0710747d"}, "mac_address": "286c0710747d", "device_type": "rgb"}}, "origin": "LOCAL", "time_fired": "2017-10-22T22:59:22.576664+00:00"}
[10/22/2017, 11:59:24 PM] [HomeAssistant] Received event: {"event_type": "platform_discovered", "data": {"service": "load_platform.light", "platform": "yeelight", "discovered": {"host": "192.168.0.19", "port": 54321, "hostname": "yeelink-light-strip1_miio48454372.local.", "properties": {"epoch": "1", "mac": "286c07141ecf"}, "mac_address": "286c07141ecf", "device_type": "strip"}}, "origin": "LOCAL", "time_fired": "2017-10-22T22:59:22.582746+00:00"}
[10/22/2017, 11:59:24 PM] [HomeAssistant] Received event: {"event_type": "platform_discovered", "data": {"service": "load_platform.light", "platform": "yeelight", "discovered": {"host": "192.168.0.20", "port": 54321, "hostname": "yeelink-light-color1_miio46001900.local.", "properties": {"epoch": "1", "mac": "f0b429b7c447"}, "mac_address": "f0b429b7c447", "device_type": "rgb"}}, "origin": "LOCAL", "time_fired": "2017-10-22T22:59:22.604092+00:00"}
[10/22/2017, 11:59:24 PM] [HomeAssistant] Received event: {"event_type": "platform_discovered", "data": {"service": "load_platform.light", "platform": "yeelight", "discovered": {"host": "192.168.0.37", "port": 54321, "hostname": "yeelink-light-color1_miio45044463.local.", "properties": {"epoch": "1", "mac": "f0b429a816f2"}, "mac_address": "f0b429a816f2", "device_type": "rgb"}}, "origin": "LOCAL", "time_fired": "2017-10-22T22:59:22.617706+00:00"}
[10/22/2017, 11:59:24 PM] [HomeAssistant] Received event: {"event_type": "platform_discovered", "data": {"service": "load_platform.light", "platform": "yeelight", "discovered": {"host": "192.168.0.36", "port": 54321, "hostname": "yeelink-light-color1_miio45084881.local.", "properties": {"epoch": "1", "mac": "f0b429a8b4d4"}, "mac_address": "f0b429a8b4d4", "device_type": "rgb"}}, "origin": "LOCAL", "time_fired": "2017-10-22T22:59:22.632362+00:00"}
[10/22/2017, 11:59:24 PM] [HomeAssistant] Received event: {"event_type": "platform_discovered", "data": {"service": "apple_tv", "discovered": {"host": "192.168.0.42", "port": 3689, "hostname": "Creative-iRoar.local.", "properties": {"txtvers": "1", "atSV": "65541", "hG": "00000000-116a-b4d4-314d-2f02916940ba", "MniT": "167845888", "fs": "2", "Name": "Creative iRoar", "PrVs": "65538", "DFID": "2", "EiTS": "1", "MiTPV": "196611"}, "name": "Creative iRoar"}}, "origin": "LOCAL", "time_fired": "2017-10-22T22:59:22.645636+00:00"}
[10/22/2017, 11:59:24 PM] [HomeAssistant] Received event: {"event_type": "platform_discovered", "data": {"service": "apple_tv", "discovered": {"host": "192.168.0.29", "port": 3689, "hostname": "Bedroom-2.local.", "properties": {"DFID": "3", "EiTS": "1", "mV": "131082", "aV": "196620", "hG": "00000000-116a-b4d4-314d-2f02916940ba", "fs": "2", "Name": "Bedroom", "atSV": "65539", "Ver": "131075"}, "name": "Bedroom"}}, "origin": "LOCAL", "time_fired": "2017-10-22T22:59:22.651384+00:00"}
[10/22/2017, 11:59:24 PM] [HomeAssistant] Received event: {"event_type": "platform_discovered", "data": {"service": "load_platform.media_player", "platform": "apple_tv", "discovered": {"name": "Creative iRoar", "host": "192.168.0.42", "login_id": "00000000-116a-b4d4-314d-2f02916940ba", "start_off": false}}, "origin": "LOCAL", "time_fired": "2017-10-22T22:59:24.832717+00:00"}
[10/22/2017, 11:59:24 PM] [HomeAssistant] Received event: {"event_type": "platform_discovered", "data": {"service": "load_platform.media_player", "platform": "apple_tv", "discovered": {"name": "Bedroom", "host": "192.168.0.29", "login_id": "00000000-116a-b4d4-314d-2f02916940ba", "start_off": false}}, "origin": "LOCAL", "time_fired": "2017-10-22T22:59:24.846056+00:00"}
[10/22/2017, 11:59:25 PM] [HomeAssistant] Received event: {"event_type": "call_service", "data": {"domain": "group", "service": "set", "service_data": {"object_id": "all_lights", "name": "all lights", "entities": ["light.ceiling_light", "light.floor_lamp", "light.gateway_light_f0b4299af831", "light.light_strip", "light.yeelight_rgb_286c0710747d", "light.yeelight_rgb_f0b429b7c447"], "visible": false}, "service_call_id": "1965415632-7"}, "origin": "LOCAL", "time_fired": "2017-10-22T22:59:24.975882+00:00"}
[10/22/2017, 11:59:25 PM] [HomeAssistant] Received event: {"event_type": "call_service", "data": {"domain": "group", "service": "set", "service_data": {"object_id": "all_lights", "name": "all lights", "entities": ["light.ceiling_light", "light.floor_lamp", "light.gateway_light_f0b4299af831", "light.light_strip", "light.yeelight_rgb_286c0710747d", "light.yeelight_rgb_f0b429b7c447"], "visible": false}, "service_call_id": "1965415632-8"}, "origin": "LOCAL", "time_fired": "2017-10-22T22:59:24.978368+00:00"}
[10/22/2017, 11:59:25 PM] [HomeAssistant] Received event: {"event_type": "call_service", "data": {"domain": "group", "service": "set", "service_data": {"object_id": "all_lights", "name": "all lights", "entities": ["light.ceiling_light", "light.floor_lamp", "light.gateway_light_f0b4299af831", "light.light_strip", "light.yeelight_rgb_286c0710747d", "light.yeelight_rgb_f0b429b7c447"], "visible": false}, "service_call_id": "1965415632-9"}, "origin": "LOCAL", "time_fired": "2017-10-22T22:59:24.981417+00:00"}
[10/22/2017, 11:59:25 PM] [HomeAssistant] Received event: {"event_type": "state_changed", "data": {"entity_id": "media_player.creative_iroar", "old_state": null, "new_state": {"entity_id": "media_player.creative_iroar", "state": "unknown", "attributes": {"media_title": "Establishing a connection to Creative iRoar...", "friendly_name": "Creative iRoar", "supported_features": 896}, "last_changed": "2017-10-22T22:59:24.984732+00:00", "last_updated": "2017-10-22T22:59:24.984732+00:00"}}, "origin": "LOCAL", "time_fired": "2017-10-22T22:59:24.984911+00:00"}
[10/22/2017, 11:59:25 PM] [HomeAssistant] Received event: {"event_type": "state_changed", "data": {"entity_id": "media_player.bedroom", "old_state": null, "new_state": {"entity_id": "media_player.bedroom", "state": "unknown", "attributes": {"media_title": "Establishing a connection to Bedroom...", "friendly_name": "Bedroom", "supported_features": 896}, "last_changed": "2017-10-22T22:59:24.989335+00:00", "last_updated": "2017-10-22T22:59:24.989335+00:00"}}, "origin": "LOCAL", "time_fired": "2017-10-22T22:59:24.989477+00:00"}
[10/22/2017, 11:59:25 PM] [HomeAssistant] Received event: {"event_type": "state_changed", "data": {"entity_id": "group.all_lights", "old_state": {"entity_id": "group.all_lights", "state": "on", "attributes": {"entity_id": ["light.ceiling_light", "light.floor_lamp", "light.gateway_light_f0b4299af831", "light.light_strip"], "order": 9, "auto": true, "friendly_name": "all lights", "hidden": true, "assumed_state": false}, "last_changed": "2017-10-22T22:59:07.896872+00:00", "last_updated": "2017-10-22T22:59:07.896872+00:00"}, "new_state": null}, "origin": "LOCAL", "time_fired": "2017-10-22T22:59:24.997244+00:00"}
/usr/lib/node_modules/homebridge-homeassistant/accessories/switch.js:35
        .setValue(newState.state === 'on', null, 'internal');
                          ^
TypeError: Cannot read property 'state' of null
    at HomeAssistantSwitch.onEvent (/usr/lib/node_modules/homebridge-homeassistant/accessories/switch.js:35:27)
    at EventSource.HomeAssistantPlatform.es.addEventListener (/usr/lib/node_modules/homebridge-homeassistant/index.js:63:19)
    at emitOne (events.js:96:13)
    at EventSource.emit (events.js:191:7)
    at _emit (/usr/lib/node_modules/homebridge-homeassistant/node_modules/eventsource/lib/eventsource.js:186:17)
    at parseEventStreamLine (/usr/lib/node_modules/homebridge-homeassistant/node_modules/eventsource/lib/eventsource.js:201:9)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-homeassistant/node_modules/eventsource/lib/eventsource.js:164:11)
    at emitOne (events.js:96:13)
    at IncomingMessage.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
/usr/bin/run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
Got SIGHUP, reloading.
No service file found in /etc/avahi/services.
recvmsg() failed: Connection reset by peer
Failed to open /etc/resolv.conf: Connection reset by peer
Got SIGTERM, quitting.
dbus[681]: [system] Reloaded configuration
Leaving mDNS multicast group on interface hassio.IPv6 with address fe80::42:53ff:feda:d296.
Leaving mDNS multicast group on interface hassio.IPv4 with address 172.30.32.1.
Leaving mDNS multicast group on interface eth0.IPv6 with address fe80::aed3:dbda:67b8:853a.
Leaving mDNS multicast group on interface eth0.IPv4 with address 192.168.0.47.
avahi-daemon 0.6.32 exiting.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by siewyc** [comment]
Upgraded to 0.56.1 and everything seems to be fixed. Homebridge is running right now.

Thanks @frenck and @drock1985!!

**Comment by frenck** [comment]
The issue with multiple default routes has been fixed and merged into the `master` branch and will be in the next release.
