### ISSUE TITLE
hombridge does not restart after exception

### ISSUE THREAD

**Issue by marhoy** [hassio-addons/addon-homebridge#62]
I'm running hass.io on a rpi3 with everything updated to the latest versions. My homebridge-addon configuration looks like this:

```json
{
  "log_level": "info",
  "avahi_interfaces": "",
  "avahi_hostname": "",
  "avahi_domainname": "local",
  "enable_ipv6": true,
  "packages": [],
  "init_commands": [],
  "plugins": [
    "homebridge-harmonyhub"
  ]
}
```

homebridge has been running happily for a long time, but today homebridge-harmonyhub (a plugin for communicating with the Logitech Harmony Hub remote control) generated an exception which caused homebridge to crash.

I though that with version 2.x, homebridge would automatically restart, but that didn't happen. Here's the last part of the logfile:

``` 
events.js:199
      throw err;
      ^
Error [ERR_UNHANDLED_ERROR]: Unhandled error. (XMPP authentication failure)
    at Client.emit (events.js:197:19)
    at Client._handleAuthState (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-client/lib/Client.js:298:10)
    at Client._handleStanza (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-client/lib/Client.js:234:12)
    at Client.onStanza (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-client/lib/Client.js:222:8)
    at emitOne (events.js:125:13)
    at Connection.emit (events.js:221:7)
    at Connection.onStanza (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:369:10)
    at StreamParser.<anonymous> (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:226:10)
    at emitOne (events.js:125:13)
    at StreamParser.emit (events.js:221:7)
    at SaxLtx.<anonymous> (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/StreamParser.js:58:14)
    at emitOne (events.js:125:13)
    at SaxLtx.emit (events.js:221:7)
    at SaxLtx._handleTagOpening (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/ltx/lib/parsers/ltx.js:28:22)
    at SaxLtx.write (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/ltx/lib/parsers/ltx.js:105:26)
    at StreamParser.write (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/StreamParser.js:123:17)
/usr/bin/run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
Got SIGHUP, reloading.
No service file found in /etc/avahi/services.
```

**Comment by frenck** [comment]
The add-on will restart services when they exit nicely.

As soon as the software running inside the Docker container is crashing, it will not try to restart to avoid endless restarting loops. Secondly, automatically restarting is not within the paradigm of Docker, upon which Hassio (and its add-ons) is designed.

Furthermore, restarting is never a fix. I would recommend you get the issue fixed by contacting the authors of the `homebridge-harmonyhub` Homebrige plugin.
