### ISSUE TITLE
Nest temperature changes not translating correctly between F and C

### ISSUE THREAD

**Issue by chriscrowe** [hassio-addons/addon-homebridge#67]
This might have been fixed upstream in Homebridge already since they're several versions ahead.

Changing Nest temperatures through the Hass.io UI works just fine but when using Homebridge (via Siri) I'm getting a failure. In checking the dev logs I saw the below traceback which would indicate that it's translating between temps and passing to the Nest API incorrectly. From what I can tell-- I asked for 68* F, it converted that to 20* C (so far so good) but then commanded Nest to set to 20* F, which is not a support temperature of course.

```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/tasks.py", line 182, in _step
    result = coro.throw(exc)
  File "/usr/lib/python3.6/site-packages/homeassistant/core.py", line 1031, in _event_to_service_call
    yield from service_handler.func(service_call)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/climate/__init__.py", line 340, in async_temperature_set_service
    yield from climate.async_set_temperature(**kwargs)
  File "/usr/lib/python3.6/asyncio/futures.py", line 332, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/climate/nest.py", line 169, in set_temperature
    self.device.target = temp
  File "/usr/lib/python3.6/site-packages/nest/nest.py", line 510, in target
    self._set('devices/thermostats', data)
  File "/usr/lib/python3.6/site-packages/nest/nest.py", line 168, in _set
    response = self._nest_api._put(path=path, data=data)
  File "/usr/lib/python3.6/site-packages/nest/nest.py", line 1590, in _put
    return self._request('PUT', path, data=data)
  File "/usr/lib/python3.6/site-packages/nest/nest.py", line 1582, in _request
    raise APIError(response)
nest.nest.APIError: Temperature F value is too low: 20.0
```

**Comment by frenck** [comment]
Thank you @chriscrowe for taking the time to post an issue.

Nevertheless, just like you've already mentioned, this is an upstream issue.
The add-on is currently up2date and running the latest versions of `homebridge` and `homebridge-homeassistant`.

It might be worthy to open this issue on the `homebridge-homeassistant` repository in order to get it fixed (if not already) and released.

**Comment by chriscrowe** [comment]
FYI-- `homebridge-assistant` claims to have had 5 more releases (`2.2.1`, `2.3.0`, `2.3.1`, `3.0.0`, `3.0.1`) since the `0.2.2` version which seems to be shipping in this repo, unless I'm missing something here.

https://github.com/home-assistant/homebridge-homeassistant/releases

**Comment by frenck** [comment]
The latest version of add-on itself is currently `v2.2.0`, this version of the add-on is running Homebridge `v0.4.33` (latest at the time of writing). The `homebridge-homeassistant` plugin used inside this add-on is running on `v3.0.2` (latest at the time of writing).

Code reference:
https://github.com/hassio-addons/addon-homebridge/blob/ceb78cc625dc30ba6131e2c587734a3e60e3e291/homebridge/Dockerfile#L26
https://github.com/hassio-addons/addon-homebridge/blob/ceb78cc625dc30ba6131e2c587734a3e60e3e291/homebridge/Dockerfile#L27

P.s. Don't look at the GitHub releases pages for NPM package versions, always look them up on npmjs.org.

**Comment by chriscrowe** [comment]
Make sense! So yes I was missing something 😆Thanks I'll see if I can track down exactly where this bug is occurring.
