### ISSUE TITLE
Plugin Params

### ISSUE THREAD

**Issue by tielur** [hassio-addons/addon-homebridge#68]
# Problem/Motivation

I'm trying to install [homebridge-dacp](https://github.com/grover/homebridge-dacp) which requires you to install it via the `--unsafe-perm`.

## Expected behavior

The plugin should install and run

## Actual behavior

I get this error when starting homebridge:
```
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 
INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 20-dbus.sh: executing... 
[cont-init.d] 20-dbus.sh: exited 0.
[cont-init.d] 30-avahi.sh: executing... 
[cont-init.d] 30-avahi.sh: exited 0.
[cont-init.d] 50-config.sh: executing... 
[cont-init.d] 50-config.sh: exited 0.
[cont-init.d] 60-ipv6-hotfix.sh: executing... 
[cont-init.d] 60-ipv6-hotfix.sh: exited 0.
[cont-init.d] 80-user-packages.sh: executing... 
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/armhf/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/armhf/APKINDEX.tar.gz
v3.7.0-46-g1061d3a8d5 [http://dl-cdn.alpinelinux.org/alpine/v3.7/main]
v3.7.0-45-g32b1d3363c [http://dl-cdn.alpinelinux.org/alpine/v3.7/community]
OK: 8876 distinct packages available
(1/1) Installing make (4.2.1-r0)
Executing busybox-1.27.2-r6.trigger
OK: 68 MiB in 52 packages
(1/12) Installing binutils-libs (2.28-r3)
(2/12) Installing binutils (2.28-r3)
(3/12) Installing gmp (6.1.2-r1)
(4/12) Installing isl (0.18-r0)
(5/12) Installing libgomp (6.4.0-r5)
(6/12) Installing libatomic (6.4.0-r5)
(7/12) Installing mpfr3 (3.1.5-r1)
(8/12) Installing mpc1 (1.0.3-r1)
(9/12) Installing gcc (6.4.0-r5)
(10/12) Installing musl-dev (1.1.18-r2)
(11/12) Installing libc-dev (0.7.1-r0)
(12/12) Installing g++ (6.4.0-r5)
Executing busybox-1.27.2-r6.trigger
OK: 182 MiB in 64 packages
(1/5) Installing libbz2 (1.0.6-r6)
(2/5) Installing libffi (3.2.1-r4)
(3/5) Installing gdbm (1.13-r1)
(4/5) Installing sqlite-libs (3.21.0-r0)
(5/5) Installing python2 (2.7.14-r2)
Executing busybox-1.27.2-r6.trigger
OK: 217 MiB in 69 packages
[cont-init.d] 80-user-packages.sh: exited 0.
[cont-init.d] 81-user-scripts.sh: executing... 
[cont-init.d] 81-user-scripts.sh: exited 0.
[cont-init.d] 82-user-plugins.sh: executing... 
> mdns@2.3.4 install /usr/lib/node_modules/homebridge-dacp/node_modules/mdns
> node-gyp rebuild
make: Entering directory '/usr/lib/node_modules/homebridge-dacp/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:0:
../src/mdns.hpp:32:20: fatal error: dns_sd.h: No such file or directory
 #include <dns_sd.h>
                    ^
compilation terminated.
make: *** [dns_sd_bindings.target.mk:150: Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
make: Leaving directory '/usr/lib/node_modules/homebridge-dacp/node_modules/mdns/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.50
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/homebridge-dacp/node_modules/mdns
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdns@2.3.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.3.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-31T23_56_57_261Z-debug.log
FATAL: Failed installing plugin homebridge-dacp
[cont-init.d] 82-user-plugins.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.
 
 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
```

## Steps to reproduce

Running this add-on with Hass.io version 0.60 with these options:

```
{
  "log_level": "info",
  "avahi_interfaces": "",
  "avahi_hostname": "",
  "avahi_domainname": "local",
  "enable_ipv6": true,
  "packages": [
    "make",
    "g++",
    "python"
  ],
  "init_commands": [],
  "plugins": [
    "homebridge-dacp"
  ]
}
```

## Proposed changes

Is it possible to pass paramters to plugins when installing? So I can pass `--unsafe-perm`?

**Comment by tielur** [comment]
Oh it looks like it is already passing that here:
https://github.com/hassio-addons/addon-homebridge/blob/fa1f4a12f74b793ff1b003f009a8a295672c18cd/homebridge/rootfs/etc/cont-init.d/82-user-plugins.sh#L11

**Comment by tielur** [comment]
I was able to fix this by including ` "avahi-dev"` in my packages. This seems to of been related to https://github.com/agnat/node_mdns/issues/60 and not related to this add-on at all.

**Comment by frenck** [comment]
@tielur Glad it worked out!
