### ISSUE TITLE
Failure on startup

### ISSUE THREAD

**Issue by perwramdemark** [hassio-addons/addon-homebridge#7]
Just tried to install and run the addon-homebridge (version 1.0.3) on hassio. Seem to be getting a 403 on an HTTP call. Running latest hassio v0.51.2.

I have added home assistant password to the /homebridge/config.json.

Any pointers?

Per

```
starting version 3.2.2
[ADD-ON] Ensuring old PID files are absent
[ADD-ON] Ensuring D-Bus unique ID exists
[ADD-ON] Starting D-Bus daemon
[ADD-ON] [DEBUG] Waiting until system bus socket is ready
[ADD-ON] Starting Avahi daemon
Found user 'avahi' (UID 86) and group 'avahi' (GID 86).
Successfully dropped root privileges.
avahi-daemon 0.6.32 starting up.
chroot.c: chroot() helper started
WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
Successfully called chroot().
Successfully dropped remaining capabilities.
chroot.c: chroot() helper got command 02
Loading service file /services/sftp-ssh.service.
Loading service file /services/ssh.service.
*** WARNING: Detected another IPv4 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***
Joining mDNS multicast group on interface hassio.IPv4 with address 172.30.32.1.
New relevant interface hassio.IPv4 for mDNS.
Joining mDNS multicast group on interface docker0.IPv4 with address 172.17.0.1.
New relevant interface docker0.IPv4 for mDNS.
Joining mDNS multicast group on interface eth0.IPv4 with address 192.168.1.2.
New relevant interface eth0.IPv4 for mDNS.
Network interface enumeration completed.
Registering new address record for fe80::a020:aaff:feb4:cc78 on veth3fa7af9.*.
Registering new address record for fe80::42:3cff:fefe:cf1c on hassio.*.
Registering new address record for 172.30.32.1 on hassio.IPv4.
Registering new address record for fe80::82f:b9ff:fe49:3a93 on veth924b4de.*.
Registering new address record for fe80::5069:2fff:fed2:c92d on vethfe884a7.*.
Registering new address record for fe80::709e:d8ff:fe08:3dd7 on vetha92f327.*.
Registering new address record for fe80::140a:33ff:fef7:74f7 on veth89604ce.*.
Registering new address record for fe80::42:7ff:fe77:16ff on docker0.*.
Registering new address record for 172.17.0.1 on docker0.IPv4.
Registering new address record for fe80::d4bf:8b1e:714a:b7b2 on eth0.*.
Registering new address record for 192.168.1.2 on eth0.IPv4.
Server startup complete. Host name is hassio.local. Local service cookie is 1064142052.
[ADD-ON] Applying HAP NodeJS IPV6 HOTFIX
patching file /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js
[ADD-ON] Starting Homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[8/25/2017, 1:00:16 PM] Loaded plugin: homebridge-homeassistant
[8/25/2017, 1:00:17 PM] Registering platform 'homebridge-homeassistant.HomeAssistant'
[8/25/2017, 1:00:17 PM] ---
[8/25/2017, 1:00:17 PM] Loaded config.json with 0 accessories and 1 platforms.
[8/25/2017, 1:00:17 PM] ---
[8/25/2017, 1:00:17 PM] Loading 1 platforms...
[8/25/2017, 1:00:17 PM] [HomeAssistant] Initializing HomeAssistant platform...
[8/25/2017, 1:00:17 PM] [HomeAssistant] Fetching HomeAssistant devices.
[8/25/2017, 1:00:17 PM] Loading 0 accessories...
undefined:1
403: Forbidden
   ^
SyntaxError: Unexpected token : in JSON at position 3
    at JSON.parse (<anonymous>)
    at Request.request [as _callback] (/usr/lib/node_modules/homebridge-homeassistant/index.js:100:38)
    at Request.self.callback (/usr/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:293:19)
```

**Comment by frenck** [comment]
@perwramdemark This is due to invalid JSON configuration file for Homebridge.
This is not a plugin error. Please validate your Homebridge configuration JSON file with a JSON linter.
