### ISSUE TITLE
Error reports about Homebridge 2.2.0

### ISSUE THREAD

**Issue by plutosherry** [hassio-addons/addon-homebridge#70]
help plz.....
I have installed Homebridge 2.2.0 on Home Assistant 0.60 and Supervisor 0.78
Here is the configuration information：
{
  "log_level": "info",
  "avahi_interfaces": "hassio",
  "avahi_hostname": "HomeKIT",
  "avahi_domainname": "local",
  "enable_ipv6": false,
  "packages": [],
  "init_commands": [],
  "plugins": []
}

The following error messages appear when homebridge is started：

Error: The requested platform 'config' was not registered by any plugin.
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:122:13)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:294:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2018-1-3 20:28:32] Loaded plugin: homebridge-homeassistant
[2018-1-3 20:28:32] Registering platform 'homebridge-homeassistant.HomeAssistant'
[2018-1-3 20:28:32] ---
[2018-1-3 20:28:32] Loaded config.json with 0 accessories and 2 platforms.
[2018-1-3 20:28:32] ---
[2018-1-3 20:28:32] Loading 2 platforms...
[2018-1-3 20:28:32] [HomeKIT] Initializing HomeAssistant platform...
[2018-1-3 20:28:32] [HomeKIT] Fetching HomeAssistant devices.
/usr/lib/node_modules/homebridge/lib/api.js:122
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'config' was not registered by any plugin.
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:122:13)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:294:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2018-1-3 20:28:42] Loaded plugin: homebridge-homeassistant
[2018-1-3 20:28:42] Registering platform 'homebridge-homeassistant.HomeAssistant'
[2018-1-3 20:28:42] ---
[2018-1-3 20:28:42] Loaded config.json with 0 accessories and 2 platforms.
[2018-1-3 20:28:42] ---
[2018-1-3 20:28:42] Loading 2 platforms...
[2018-1-3 20:28:42] [HomeKIT] Initializing HomeAssistant platform...
[2018-1-3 20:28:42] [HomeKIT] Fetching HomeAssistant devices.
/usr/lib/node_modules/homebridge/lib/api.js:122
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'config' was not registered by any plugin.
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:122:13)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:294:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2018-1-3 20:28:50] Loaded plugin: homebridge-homeassistant
[2018-1-3 20:28:51] Registering platform 'homebridge-homeassistant.HomeAssistant'
[2018-1-3 20:28:51] ---
[2018-1-3 20:28:51] Loaded config.json with 0 accessories and 2 platforms.
[2018-1-3 20:28:51] ---
[2018-1-3 20:28:51] Loading 2 platforms...
[2018-1-3 20:28:51] [HomeKIT] Initializing HomeAssistant platform...
[2018-1-3 20:28:51] [HomeKIT] Fetching HomeAssistant devices.
/usr/lib/node_modules/homebridge/lib/api.js:122
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'config' was not registered by any plugin.
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:122:13)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:294:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

**Comment by frenck** [comment]
@plutosherry Could you please supply your homebridge configuration as well?

**Comment by plutosherry** [comment]
@frenck 
thanks alot and there is my homebridge conf

```
{
  "bridge": {
    "name": "Homebridge",
    "username": "A8:07:BA:03:02:D3",
    "port": 51826,
    "pin": "123-45-678"
  },
  "description": "Homebridge for Home Assistant",
  "accessories": [],
  "platforms": [
    {
      "platform": "HomeAssistant",
      "name": "HomeKIT",
      "host": "http://192.168.1.10:8123",
      "password": "mypassword",
      "default_visibility": "visible",
      "supported_types": [
        "automation",
        "binary_sensor",
        "climate",
        "cover",
        "device_tracker",
        "fan",
        "group",
        "input_boolean",
        "light",
        "lock",
        "media_player",
        "remote",
        "scene",
        "script",
        "sensor",
        "switch",
        "vacuum"
      ],
      "logging": true,
      "verify_ssl": true
    }
  ]
}
```

**Comment by frenck** [comment]
Change it to this:

```
{
  "bridge": {
    "name": "Homebridge",
    "username": "A8:07:BA:03:02:D3",
    "port": 51826,
    "pin": "123-45-678"
  },
  "description": "Homebridge for Home Assistant",
  "accessories": [],
  "platforms": [
    {
      "platform": "HomeAssistant",
      "name": "HomeAssistant",
      "host": "http://hassio/homeassistant",
      "password": "",
      "default_visibility": "visible",
      "supported_types": [
        "automation",
        "binary_sensor",
        "climate",
        "cover",
        "device_tracker",
        "fan",
        "group",
        "input_boolean",
        "light",
        "lock",
        "media_player",
        "remote",
        "scene",
        "script",
        "sensor",
        "switch",
        "vacuum"
      ],
      "logging": true,
      "verify_ssl": true
    }
  ]
}
```

Changes:
- platform name
- host URL (yes, use that one)
- password (yes, leave it empty)

**Comment by plutosherry** [comment]
@frenck 
[2018-1-5 08:52:57] Homebridge is running on port 51826.
Thank you very much. After modifying the config.json configuration, it looks like homebridge is running normally

PS: But one thing I don't understand is that I have a homeassistant password. Why don't you have to fill in the password here?  ("password": "",)

**Comment by frenck** [comment]
@plutosherry Glad your issue was resolved!

The URL is now set to `http://hassio/homeassistant/`, which is an internal "magical" URL. All add-ons in Hass.io can use that to directly connect to Home Assistant via an internal network. This by-passes the Home Assistant authentication, so that's why it is left empty.
