### ISSUE TITLE
Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by pyrosmiley** [hassio-addons/addon-homebridge#90]
# Problem/Motivation

> Not entirely sure what happened/changed, but the plugin now will not start. I noticed the change about a day after activating the MQTT broker built in to Hass.io, but it worked just fine shortly after, and I made no changes since.

## Expected behavior

> I do not currently have any MQTT devices set up, but I do have a couple of Wemo switches and some thermostats which normally show up just fine. 

## Actual behavior

> I noticed in the logs that it's finding 0 devices in homeassistant to pass on, which is definitely not the case. 

## Steps to reproduce

> I have tried disabling the MQTT plugin in my config, to no avail. I have no idea what else might be causing this -- it's a fairly fresh install in a fresh virtual machine. The only non-discoverable component is the Nest thermostats and they were working just fine. attached are the logs with error messages that come up each time I restart the plugin.
```
[2018-5-5 22:42:23] Loaded plugin: homebridge-homeassistant
[2018-5-5 22:42:23] Registering platform 'homebridge-homeassistant.HomeAssistant'
[2018-5-5 22:42:23] ---
[2018-5-5 22:42:23] Loaded config.json with 0 accessories and 1 platforms.
[2018-5-5 22:42:23] ---
[2018-5-5 22:42:23] Loading 1 platforms...
[2018-5-5 22:42:23] [HomeAssistant] Initializing HomeAssistant platform...
[2018-5-5 22:42:23] [HomeAssistant] Fetching HomeAssistant devices.
[2018-5-5 22:42:23] Loading 0 accessories...
undefined:1
<html><head><title>500 Internal Server Error</title></head><body><h1>500 Internal Server Error</h1>Server got itself in trouble</body></html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request.request [as _callback] (/usr/lib/node_modules/homebridge-homeassistant/index.js:101:38)
    at Request.self.callback (/usr/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
```

## Proposed changes

> ¯\\_(ツ)_/¯

**Comment by rileytron** [comment]
I’m receiving this same error. I thought it was because I updated HassIO, but I downgraded and I’m still receiving this error.

**Comment by frenck** [comment]
Is there an error visible in the Supervisor logs?
The error seems to be coming from the supervisor since it throws a 500 error.

**Comment by sfanicola** [comment]
same here! I tried to reinstall all... same error...huh

**Comment by andyrooo82** [comment]
I'm having the same issue. I'm still on version 0.67.1. 
@frenck yes there is an error visible in the supervisor logs.

> 18-05-06 07:37:48 WARNING (MainThread) [hassio.api.proxy] Unknown Home-Assistant API access!
18-05-06 07:37:48 INFO (MainThread) [hassio.api.proxy] Home-Assistant EventStream start
18-05-06 07:37:48 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 381, in start
    resp = await self._request_handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web_app.py", line 322, in _handle
    resp = await handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 88, in impl
    return await handler(request)
  File "/usr/lib/python3.6/site-packages/hassio/api/security.py", line 36, in token_validation
    return await handler(request)
  File "/usr/lib/python3.6/site-packages/hassio/api/proxy.py", line 77, in stream
    client = await self._api_client(request, 'stream', timeout=None)
  File "/usr/lib/python3.6/site-packages/hassio/api/proxy.py", line 37, in _api_client
    method = getattr(self._websession_ssl, request.method.lower())
  File "/usr/lib/python3.6/site-packages/hassio/coresys.py", line 269, in __getattr__
    raise AttributeError()
AttributeError
18-05-06 07:37:48 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states access from a0d7b954_homebridge
18-05-06 07:37:48 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 381, in start
    resp = await self._request_handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web_app.py", line 322, in _handle
    resp = await handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 88, in impl
    return await handler(request)
  File "/usr/lib/python3.6/site-packages/hassio/api/security.py", line 36, in token_validation
    return await handler(request)
  File "/usr/lib/python3.6/site-packages/hassio/api/proxy.py", line 108, in api
    client = await self._api_client(request, path)
  File "/usr/lib/python3.6/site-packages/hassio/api/proxy.py", line 37, in _api_client
    method = getattr(self._websession_ssl, request.method.lower())
  File "/usr/lib/python3.6/site-packages/hassio/coresys.py", line 269, in __getattr__
    raise AttributeError()
AttributeError

**Comment by frenck** [comment]
This issue has been fixed upstream in the Supervisor. Release 103.2 fixes it.

To upgrade:

![](http://g.recordit.co/ZbO5PRMkn1.gif)
