### ISSUE TITLE
Homebridge add-on starting in error after upgrading to Home Assistant 0.72

### ISSUE THREAD

**Issue by bonanitech** [hassio-addons/addon-homebridge#96]
After I updated Home Assistant to version 0.72, the Homebridge add-on is returning the following error during the start process:

```
[2018-6-23 08:16:28] Homebridge is running on port 51826.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Service name is already in use on the network
    at Registry._onProbeComplete (/usr/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js:106:27)
    at Prober.done (/usr/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:67:10)
    at Prober.onMDNSresponse (/usr/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:61:102)
    at emitTwo (events.js:126:13)
    at EventEmitter.emit (events.js:214:7)
    at Socket.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/multicast-dns/index.js:49:43)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage [as onmessage] (dgram.js:658:8)
```

Except for the HA version upgrade and a small test with the Lovelace UI, nothing else was changed in the configuration.

**Comment by bonanitech** [comment]
My bad. It was a misconfiguration in the Avahi service in my network. My IoT devices are in a separate network, so I need this service to be able to access them from the LAN.
